mongodb:
  uri: mongodb://localhost:27017/
  database: yolo_validation
  collections:
    sources: sources
    models: models
    detections: detections

yolo:
  dataset_base_dir: /home/fred/dataset
  confidence_threshold: 0.25
  iou_threshold: 0.45
  model:
    image_size: [800, 800]
    device: cuda  # Will fall back to cpu if cuda not available
    
flask:
  secret_key: your-secret-key
  debug: true
  host: 0.0.0.0
  port: 8765
  socket:
    cors_allowed_origins: "*"
    async_mode: threading

rtsp:
  buffer_size: 1
  frame:
    width: 800
    height: 800

logging:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s'
  date_format: '%Y-%m-%d %H:%M:%S'

packages:
  torch: 2.4.0
  torchvision: 0.19.0
  opencv: 4.10.0.84
  ultralytics: 8.2.82
  numpy: 1.23.5
  flask: 3.0.3
  python_socketio: 0.23.1
